### ISSUE TITLE
Package assumes autopublish: Did not receive an index or an array of indexes (using subscribe/publish)

### ISSUE THREAD

**Issue by methodbox** [matteodem/meteor-easy-search#319]
```
let Players = new Meteor.Collection('players'),
  PlayersIndex = new EasySearch.Index({
    collection: Players,
    fields: ['name'],
    engine: new EasySearch.MongoDB()
  });

Template.searchBox.helpers({
  playersIndex: () => PlayersIndex
});
```

Where exactly is this supposed to go? The ```let``` syntax is read as invalid by the linter in Meteor. This indicates to me it needs to go into a ```helper```, but this doesn't make sense due to the fact that you're creating a new collection.

The previous syntax to create an index appeared like this:

```
Trackers.initEasySearch(
  [
    'stuff'
  ], {
  'limit': 5,
  'use': 'mongo-db'
});
```
....which appears to still work.

I've checked your documentation on the site, but this is completely inconsistent across the site.

Maybe this should be titled "fix your documentation". 

I can't seem to get even a basic search working with version 2.0.

**Comment by methodbox** [comment]
I've found that adding this:
```
ReportsIndex = new EasySearch.Index({
  collection: Trackers,
  fields: ['repFirstName'],
  engine: new EasySearch.MongoDB()
});
```
.. on a server-side collection (assuming you're NOT using auto-publish) doesn't throw the syntax error like the example, however, it still doesn't work and appears to be an issue with blaze-components.  I'm getting this in the browser console:

```
TypeError: index.getComponentDict is not a function
    at base.js:47
    at base.js:112
    at arrayEach (erasaur_meteor-lodash.js:1297)
    at Function.<anonymous> (erasaur_meteor-lodash.js:3353)
    at InputComponent.eachIndex (base.js:111)
    at InputComponent.onCreated (base.js:46)
    at InputComponent.onCreated (input.js:11)
    at registerHooks.onCreated (peerlibrary_blaze-components.js:736)
    at template.js:116
    at Function.Template._withTemplateInstanceFunc (template.js:457)
```

**Comment by matteodem** [comment]
1. According to the [UPGRADE-2.0.md](https://github.com/matteodem/meteor-easy-search/blob/master/UPGRADE-2.0.md) the package code now uses ES2015, which means that all the examples also use ES2015 code. If `let` is invalid, then you're missing the `ecmascript` package.

2. Might be an issue that has to do with not having ES2015 available in your project.

Which version of meteor are you using?

**Comment by jpbourgeon** [comment]
This might help.

The getComponentDict method is not available before the template has been rendered. You cannot access it from the helpers otherwise it will return undefined. However it is available in the onRendered method and in the events.

Here is how I access the count in my helpers, through a session variable :

```javascript
Template.collectivities.onRendered(function() {
  Tracker.autorun(function() {
    var dict = index.getComponentDict();
    Session.set('count', dict.get('count'));
});

Template.collectivities.helpers({
  count: function() {
    return Session.get('count');
  }
});
```

**Comment by matteodem** [comment]
This should also work https://github.com/matteodem/easy-search-leaderboard/blob/master/leaderboard.js#L56, so the getComponentDict() should be already defined before.

**Comment by matteodem** [comment]
Also show me your package list or a reproduction repository, because the old code (`initEasySearch` is clearly gone and it looks like there are messed up dependencies in your app).

**Comment by jpbourgeon** [comment]
Hi Matteo

The code throws
```javascript
Exception in template helper: TypeError: Cannot read property 'get' of undefined
    at Object.Template.templateName.helpers.resultsCount
```

The only way for me to get the component dict is through a ``Session`` variable.

Do I miss something ? Do you have a clue ?

**Comment by matteodem** [comment]
Are you using `easy:search`? Can I see the package list?

**Comment by jpbourgeon** [comment]
I use easy-search :-) See below my packages 
```
accounts-base@1.2.1
accounts-password@1.1.3
alanning:roles@1.2.14
aldeed:autoform@5.7.1
aldeed:collection2@2.5.0
aldeed:simple-schema@1.3.3
autoupdate@1.2.3
babel-compiler@5.8.24_1
babel-runtime@0.1.4
base64@1.0.4
binary-heap@1.0.4
blaze@2.1.3
blaze-html-templates@1.0.1
blaze-tools@1.0.4
boilerplate-generator@1.0.4
caching-compiler@1.0.0
caching-html-compiler@1.0.2
callback-hook@1.0.4
check@1.0.6
chhib:selectize-bootstrap-3@0.0.1
chuangbo:cookie@1.1.0
coffeescript@1.0.10
comerc:autoform-selectize@2.2.3
ddp@1.2.2
ddp-client@1.2.1
ddp-common@1.2.1
ddp-rate-limiter@1.0.0
ddp-server@1.2.1
deps@1.0.9
diff-sequence@1.0.1
dispatch:run-as-user@1.1.1
easy:search@2.0.0
easysearch:components@2.0.1
easysearch:core@2.0.1
ecmascript@0.1.5
ecmascript-collections@0.1.6
ejson@1.0.7
email@1.0.7
erasaur:meteor-lodash@3.10.1_1
fastclick@1.0.7
geojson-utils@1.0.4
harrison:papa-parse@1.1.0
hot-code-push@1.0.0
html-tools@1.0.5
htmljs@1.0.5
http@1.1.1
id-map@1.0.4
iron:controller@1.0.12
iron:core@1.0.11
iron:dynamic-template@1.0.12
iron:layout@1.0.12
iron:location@1.0.11
iron:middleware-stack@1.0.11
iron:router@1.0.12
iron:url@1.0.11
jquery@1.11.4
launch-screen@1.0.4
less@2.5.0_3
livedata@1.0.15
localstorage@1.0.5
logging@1.0.8
mantarayar:shortid@0.0.1
meteor@1.1.9
meteor-base@1.0.1
meteorhacks:fast-render@2.10.0
meteorhacks:inject-data@1.4.1
meteorhacks:picker@1.0.3
minifiers@1.1.7
minimongo@1.0.10
mobile-experience@1.0.1
mobile-status-bar@1.0.6
momentjs:moment@2.10.6
mongo@1.1.2
mongo-id@1.0.1
mongo-livedata@1.0.9
mrt:flash-messages@1.0.1
multiply:iron-router-progress@1.0.2
npm-bcrypt@0.7.8_2
npm-mongo@1.4.39_1
observe-sequence@1.0.7
ongoworks:security@1.3.0
ordered-dict@1.0.4
peerlibrary:assert@0.2.5
peerlibrary:base-component@0.14.0
peerlibrary:blaze-components@0.15.0
peerlibrary:computed-field@0.3.0
peerlibrary:reactive-field@0.1.0
promise@0.5.0
random@1.0.4
rate-limit@1.0.0
reactive-dict@1.1.2
reactive-var@1.0.6
reload@1.1.4
retry@1.0.4
routepolicy@1.0.6
service-configuration@1.0.5
session@1.1.1
sha@1.0.4
softwarerero:accounts-t9n@1.1.4
spacebars@1.0.7
spacebars-compiler@1.0.7
srp@1.0.4
standard-minifiers@1.0.1
templating@1.1.4
templating-tools@1.0.0
tracker@1.0.9
twbs:bootstrap@3.3.5
ui@1.0.8
underscore@1.0.4
url@1.0.5
useraccounts:bootstrap@1.12.4
useraccounts:core@1.12.4
webapp@1.2.2
webapp-hashing@1.0.5
```

**Comment by matteodem** [comment]
It might be that `getComponentDict()` returns undefined, as long as getComponentDict is a function that's fine.

**Comment by methodbox** [comment]
Yes I'm using easy:search.

I've restored my app to before adding easy:search, removed the old search and still get this:

```
Error: Did not receive an index or an array of indexes: "reportsIndex" [invalid-configuration]
    at InputComponent.onCreated (base.js:41)
    at InputComponent.onCreated (input.js:11)
    at registerHooks.onCreated (peerlibrary_blaze-components.js:650)
    at template.js:116
    at Function.Template._withTemplateInstanceFunc (template.js:457)
    at fireCallbacks (template.js:112)
    at null.<anonymous> (template.js:192)
    at fireCallbacks (view.js:279)
    at Object.Tracker.nonreactive (tracker.js:589)
    at view.js:276
```

Note that I am NOT using AUTOPUBLISH. This means if I have an EXISTING collection, your example is wrong - I will get an error indicating that a collection 'this name' already exists.

The same happens when I use this:

```
let reportsIndex = new EasySearch.Index({
  collection: Trackers,
  fields: [
    'leadFirstName',
    'leadLastName',
    'repFirstName',
    'repLastName'
    ],
  engine: new EasySearch.MongoDB()
});
```
```
Uncaught Error: There is already a collection named 'trackers/easySearch'
```

You were correct - emcascript was not installed, but my helper was recreated like this:
```
Template.reportsHome.helpers ({
  reportsIndex: function() {
    return ReportsIndex
});
```

I've added the correct package, but with the same error at the top of THIS post: it doesn't find the index.

**Comment by methodbox** [comment]
This my list:
```
alexgreg:materialize-clockpicker  0.0.1  Clock picker for materializecss
blaze-html-templates              1.0.1  Compile HTML templates into reactive UI with Meteor...
check                             1.0.6  Check whether a value matches a pattern
easy:search                       2.0.0  Easy-to-use search with Blaze Components (+ Elastic...
ecmascript                        0.1.5  Compiler plugin that supports ES2015+ in all .js files
ejson                             1.0.7  Extended and Extensible JSON library
insecure                          1.0.4  (For prototyping only) Allow all database writes fr...
iron:router                       1.0.12  Routing specifically designed for Meteor
jquery                            1.11.4  Manipulate the DOM using CSS selectors
logging                           1.0.8  Logging facility.
maazalik:highcharts               0.4.0  HighCharts for Meteor, with an easy to use helper t...
materialize:materialize           0.97.0* Materialize (official): A modern responsive front-...
meteor-base                       1.0.1  Packages that every Meteor app needs
mobile-experience                 1.0.1  Packages for a great mobile user experience
mongo                             1.1.2  Adaptor for using MongoDB and Minimongo over DDP
random                            1.0.4  Random number generator and utilities
reload                            1.1.4  Reload the page while preserving application state.
session                           1.1.1  Session variable
simonhochrein:material-icons      0.0.2  A Meteor wrapper for Google's Material Icons
spacebars                         1.0.7  Handlebars-like template language for Meteor
standard-minifiers                1.0.1  Standard minifiers used with Meteor apps by default.
tracker                           1.0.9  Dependency tracker to allow reactive callbacks
```

**Comment by methodbox** [comment]
Also, I'm not explicitly USING ```getComponentDict```.

**Comment by methodbox** [comment]
Note that your example HERE: http://matteodem.github.io/meteor-easy-search/getting-started/ for creating an index does not match your example HERE:  http://matteodem.github.io/meteor-easy-search/.

Neither works, anyway, but it's inconsistent.

My guess is your package assumes someone is using ```autopublish```, which is a bad assumption as this would only be the case in development.

When I add the index config to my ```Meteor.publish``` function, it seems to recognize this exact issue: the terminal returns an error, but still runs the app: ```Ignoring duplicate publish named...``` .

**Comment by methodbox** [comment]
@jpbourgeon I see you are NOT using ```autopublish```, but you are using ```Session.get```.  Do you know if this worked BEFORE you removed ```autopublish```.

**Comment by jpbourgeon** [comment]
@methodbox I came to use ``easy:search`` after I removed ``autopublish``

FYI: I added ``autopublish`` back in my code a minute ago for testing purpose. ``getComponentDict`` stays unavailable in my helpers.

**Comment by matteodem** [comment]
* This package does not assume that you use autopublish, it creates it's own non-conflicting subscription / publications
* The error `Did not receive an index or an array of indexes` clearly states that it received a string instead of the index instance: http://matteodem.github.io/meteor-easy-search/docs/core/
* I created a new issue for having consistent "index creation" in the docs

I'm not really sure what the problem / purpose of this issue is as it's a collection of different things that don't seem to be one problem. Please create a new issue if you still have problems with a clear description and reproduction repo or steps and what the "expected behaviour" is.

**Comment by matteodem** [comment]
Also I didn't create "consistent indexes" because every part of the doc explains different things, so it doesn't make sense to be consistent across pages.

**Comment by methodbox** [comment]
I'm sorry but that error does not clearly state that it received a string.

You still haven't answered my question as to where in the code any of this is supposed to go.

Adding your example code, replacing as needed for my app, results in the error you're saying is caused by a string instead of an index. WHAT is saying it received a string? If it's your package, then either the package has issues or your docs are wrong.

As you can see in my example code above, I'm not passing the index name or collection name as a string.

This error is coming from YOUR view code for the search field where you specify the index; this is from the web console.

The Meteor console outputs a concern with multiple collections using your default configuration.

Inserting your code into the subscribe and publish functions, removing the collection value resolves the statement about ignoring duplicate collections.

This means your package doesn't seem to be able to be used to search an EXISTING collection.

I don't understand how creating an entirely new collection does me any good, anyway. I need to search existing records.

If it's necessary to publish a sub-collection for searching, then this should be in your docs.

As it stands, it creates a new, empty collection which is useless.

In @jpbourgeon example he is using the session variable and onRendered to control when the query is run, which isn't even in your docs. I think it's safe to say that how easy:search utilizes the local collection has problems.

In my case, I need to search an existing collection. If a new, local collection is needed to do that, or the session variable is required this should be in the docs. 

I see nothing provided in your answers as to why I would need to create a new collection on the server when there is an existing collection. Mongo indexes can be created in mongo shell and accessed from the client on existing collections; making a new local collection seems useless and a server collection is redundant.

**Comment by matteodem** [comment]
There are a lot of assumptions being made in this issue, which none of are true. I also don't understand what _any of the code_ is supposed to mean. You don't need to be rude because something's not working, I appreciate clearly constructed questions more or bug issues that state what the problem is and have reproducable outcomes.

My docs clearly state where the code needs to go. It's not done everywhere but I can do that if it that makes things simpler for you.

Feel free to create a new github issue where you state what your problem is and give me reproduction steps / repo to understand what it is or ask me any question, but not multiple in one post. Thanks :)
